apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: neurosleep
type: Opaque
stringData:
  DB_HOST: "mysql"
  DB_USERNAME: "root"
  DB_PASSWORD: "rootpassword"
  DB_DATABASE: "neurosleep"
