apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: neurosleep
spec:
  type: NodePort       # <- ini
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500  # port bebas antara 30000-32767
